### ISSUE TITLE
用户管理列表过滤

### ISSUE THREAD

**Issue by ryanxia2016** [continew-org/continew-admin-ui-arco#4]
### Bug 描述

用户管理界面中，点击根节点 “Xxx科技有限公司”
第一次点击，列表中只会显示admin用户，再次点击 “Xxx科技有限公司”，此时会显示2条记录，admin和test

### 复现步骤

1.用户管理界面中，点击根节点 “Xxx科技有限公司”
2.第一次点击，列表中只会显示admin用户，再次点击 “Xxx科技有限公司”，此时会显示2条记录，admin和test

### 预期结果

重复点击相同节点，有相同的结果

### 环境信息

JDK 17 Springboot 3.1

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
目前的设计是，点击选中，再点击即取消选中。不过也许可以添加一个 `x` 按钮，来表示可以取消选中，这样多次点击，选中状态不变。
![image](https://github.com/Charles7c/continew-admin-ui/assets/25446948/7f82213f-eeb6-4d10-ba11-327cd1b2840e)
![image](https://github.com/Charles7c/continew-admin-ui/assets/25446948/d9d24c27-e637-4057-a78c-96e1c7a11f4d)

**Comment by Charles7c** [comment]
这个小细节我先记下了，后面看情况可以加一下。或者欢迎大佬提交 PR。
